analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#050708'
    - '#f16623'
    - '#a9a9a9'
    - '#71452e'
  brandStrength: 0.5
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.5
cta: {}
layout_spectrum: 0.773848
name: inloves
opengraph: {}
purpose: []
typography_spectrum: 0.13551
