name: inloves
favicon: null
layout_spectrum: 0
typography_spectrum: 0.21649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#000001'
    - '#e7e715'
    - '#cccdcd'
    - '#626263'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.8426895255688578
  rhythmicContrast: 0.42436776240356266
purpose: []
