name: inloves
favicon: null
layout_spectrum: 0.7960847665090114
typography_spectrum: 0.9719009923283011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6284262414555997
  lightness: 0.35252988105639815
  saturation: 0.8426895255688578
  rhythmicContrast: 0.42436776240356266
purpose: []
